version: '3'

volumes:
  bundle:
  db:

services:
  db:
    image: postgres:12.4
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    depends_on:
      - db
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    tmpfs: /app/tmp
    env_file: app.env
    tty: true
    stdin_open: true
    ports:
      - "3000:3000"
