version: "3.9"

volumes:
  bundle:

services:
  web: &rails
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    volumes:
      - .:/app
      - bundle:/usr/local/bundle
      - ./node_modules:/app/node_modules
    ports:
      - "3000:3000"
    tmpfs: /app/tmp
    env_file: app.env
    tty: true
    stdin_open: true
    logging:
      driver: json-file
      options:
        max-size: 1m
        max-file: '10'
